In [1]:
# Importing Numpy Library
import numpy as np

In [2]:
# Assignment 2, Exerc. 1 : Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array.

# Creating a 4x5 2D NumPy array with random integers between 1 and 10
array_2d = np.random.randint(1, 11, size=(4, 5))

print("2D Array:")
print(array_2d)

# Finding the maximum value of the entire array
max_value = np.max(array_2d)

print("\nMaximum value of the entire array:", max_value)



2D Array:
[[4 6 5 3 9]
 [9 1 3 7 3]
 [8 6 5 4 4]
 [8 9 9 8 6]]

Maximum value of the entire array: 9


In [3]:
# Assignment 2, Exerc. 2 : Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

# Creating a 1D NumPy array of size 20 with random floats between 0 and 1
array_1d = np.random.random(20)

# Reshaping the array into a 4x5 matrix
array_2d = array_1d.reshape(4, 5)

print("Original 2D Array:")
print(array_2d)

# Computing the mean of each row
row_means = np.mean(array_2d, axis=1)

print("\nMean of each row:")
print(row_means)


Original 2D Array:
[[0.20644311 0.71806728 0.62744882 0.73424716 0.30983444]
 [0.3700544  0.40791357 0.65276474 0.72932752 0.92487246]
 [0.72486257 0.74565844 0.55103498 0.03037141 0.43602991]
 [0.59714919 0.60623611 0.06354576 0.09714707 0.16356929]]

Mean of each row:
[0.51920816 0.61698654 0.49759146 0.30552948]


In [4]:
# Assignment 2, Exerc. 3 : Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

# Creating a 5x5 2D NumPy array with random integers between 1 and 100
array_2d = np.random.randint(1, 101, size=(5, 5))

print("2D Array:")
print(array_2d)

# Computing the standard deviation of each column
column_std_dev = np.std(array_2d, axis=0)

print("\nStandard deviation of each column:")
print(column_std_dev)


2D Array:
[[ 5 86 35 19 87]
 [ 6 64 36 85 27]
 [89 85 69 75 66]
 [27 13 35  9 63]
 [99 21 76 64 17]]

Standard deviation of each column:
[40.73524273 31.16023106 18.34557167 30.61764197 26.04611295]


In [5]:
# Assignment 2, Exerc. 4 : Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

# Creating a 1D NumPy array of size 15 with random floats between -10 and 10
array_1d = np.random.uniform(-10, 10, 15)

print("Original Array:")
print(array_1d)

# Replacing negative values with their absolute values
array_1d = np.abs(array_1d)

print("\nArray with negative values replaced by their absolute values:")
print(array_1d)


Original Array:
[-6.5895412   4.0950252  -6.81831989 -5.90647672  0.4966918  -7.29010514
  9.69238474 -7.60448227 -9.56760326 -8.33896191  8.21608089  5.60386739
  1.06238971 -3.83397883  9.92769158]

Array with negative values replaced by their absolute values:
[6.5895412  4.0950252  6.81831989 5.90647672 0.4966918  7.29010514
 9.69238474 7.60448227 9.56760326 8.33896191 8.21608089 5.60386739
 1.06238971 3.83397883 9.92769158]


In [6]:
# Assignment 2, Exerc. 5 :  Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

# Creating a 3x4 2D NumPy array with random integers between 1 and 100
array_2d = np.random.randint(1, 101, size=(3, 4))

print("2D Array:")
print(array_2d)

# Calculating the sum of all elements in the array
total_sum = np.sum(array_2d)

print("\nSum of all elements in the array:", total_sum)


2D Array:
[[22 54 15  4]
 [ 3 97 51 46]
 [10 33 69 56]]

Sum of all elements in the array: 460


In [7]:
# Assignment 2, Exerc. 7 : Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

# Creating a 4x6 2D NumPy array with random floats between 0 and 1
array_2d = np.random.random((4, 6))

print("Original Array:")
print(array_2d)

# Calculating the mean and standard deviation of each column
column_means = np.mean(array_2d, axis=0)
column_stddevs = np.std(array_2d, axis=0)

# Normalizing each column
normalized_array = (array_2d - column_means) / column_stddevs

print("\nNormalized Array:")
print(normalized_array)


Original Array:
[[0.81651621 0.84041048 0.6951419  0.28924512 0.83295372 0.52487803]
 [0.54045995 0.13178863 0.55485918 0.8421119  0.49312476 0.16577913]
 [0.55915803 0.39667277 0.01910855 0.55131404 0.17843916 0.2500738 ]
 [0.10405238 0.85265374 0.91032531 0.53804761 0.11291244 0.44532664]]

Normalized Array:
[[ 1.21703126  0.93185616  0.45694602 -1.35815418  1.49774225  1.23418438]
 [ 0.13837341 -1.38486763  0.03040702  1.46539144  0.31019976 -1.2505949 ]
 [ 0.21143398 -0.51887204 -1.59857859 -0.01974213 -0.78947846 -0.66731922]
 [-1.56683866  0.97188351  1.11122556 -0.08749513 -1.01846355  0.68372974]]


In [9]:
# Assignment 2, Exerc. 8 : Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

# Creating a 10x10 2D NumPy array with random integers between 1 and 100
array_2d = np.random.randint(1, 101, size=(10, 10))

print("Original Array:")
print(array_2d)

# Replacing values greater than 50 with 1 and others with 0
binary_array = np.where(array_2d > 50, 1, 0)

print("\nBinary Array (values > 50 replaced with 1, others with 0):")
print(binary_array)


Original Array:
[[ 19  18  23  28   2  29 100   2  80  82]
 [ 45  27   2   9  69  95   4   2  46   1]
 [ 44  69  47  74  18  99  58   3  47  93]
 [ 84  53  36  68   3  56  91   5  73  69]
 [ 77  34  14   6  39  62  30  51  18  93]
 [ 58  83   1  96  75   1  28  83  62  81]
 [ 63  44  63  85  60  34  98  69  65  16]
 [ 57  57  65  53  68  11  40  47  63  11]
 [ 33  73  51  81  32  77  76  30  99  49]
 [ 99  15  39   9  55  77   7   1  93  99]]

Binary Array (values > 50 replaced with 1, others with 0):
[[0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 1 1 0 0 0 0]
 [0 1 0 1 0 1 1 0 0 1]
 [1 1 0 1 0 1 1 0 1 1]
 [1 0 0 0 0 1 0 1 0 1]
 [1 1 0 1 1 0 0 1 1 1]
 [1 0 1 1 1 0 1 1 1 0]
 [1 1 1 1 1 0 0 0 1 0]
 [0 1 1 1 0 1 1 0 1 0]
 [1 0 0 0 1 1 0 0 1 1]]


In [14]:
# Assignment 2, Exerc. 9 : Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

# Creating a 1D NumPy array of size 50 with random floats between 0 and 1
array_1d = np.random.random(50)

print("Original Array:")
print(array_1d)

# Counting the number of elements greater than 0.5
count_greater_than_0_5 = np.sum(array_1d > 0.5)

print("\nNumber of elements greater than 0.5:", count_greater_than_0_5)


Original Array:
[0.4091697  0.46849281 0.5805579  0.92891344 0.95121596 0.94069214
 0.52399329 0.95688808 0.12732635 0.25768235 0.16492533 0.88272699
 0.6405396  0.36268187 0.15949937 0.58730881 0.86683651 0.64731204
 0.83012101 0.74806593 0.06731663 0.02756846 0.78261487 0.97505509
 0.73867743 0.08161799 0.0759106  0.07413288 0.25617491 0.31766405
 0.87036092 0.17611611 0.75986361 0.49754298 0.1370223  0.13688929
 0.46732293 0.98315616 0.7949391  0.12924214 0.2201473  0.11518609
 0.93900266 0.01921679 0.02517919 0.51381434 0.52671014 0.77575985
 0.44452108 0.45478781]

Number of elements greater than 0.5: 24


In [15]:
# Assignment 2, Exerc. 10 : Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

# Create a 5x5 2D NumPy array with random floats between -1 and 1
array_2d = np.random.uniform(-1, 1, size=(5, 5))

print("Original Array:")
print(array_2d)

# Find the absolute difference between the maximum and minimum values in each row
absolute_diff_row = np.abs(np.max(array_2d, axis=1) - np.min(array_2d, axis=1))

print("\nAbsolute difference between max and min values in each row:")
print(absolute_diff_row)


Original Array:
[[-0.60265148 -0.45541373  0.33934554 -0.70257156 -0.55542329]
 [-0.30848585  0.06515634  0.01879853 -0.47675832 -0.59412685]
 [ 0.16806588 -0.75512731  0.64541642 -0.42679568 -0.05509605]
 [-0.0017425  -0.96013622  0.97793322  0.78039648 -0.05911913]
 [ 0.68755714  0.49105338 -0.02896776  0.66404762 -0.96975819]]

Absolute difference between max and min values in each row:
[1.04191711 0.65928319 1.40054374 1.93806943 1.65731534]
